version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic_user
      MYSQL_PASSWORD: petclinic_password
    ports:
      - "3306:3306"

  app:
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic_user
      SPRING_DATASOURCE_PASSWORD: petclinic_password
    ports:
      - "8080:8080"
    depends_on:
      - db

